# Generated by Django 4.0.1 on 2022-04-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_check_out_model_chkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_out_model',
            name='chkins',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='website.check_in_model'),
            preserve_default=False,
        ),
    ]
